package com.example.iic_scanner;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;
import java.util.List;

public class register extends AppCompatActivity {

    private Button register;
    private EditText username;
    public EditText idnumber;
    private EditText mailid;
    private EditText Password;
    private EditText mobilenumber;
    private Spinner department;
    private String dept;
    private FirebaseAuth fAuth;
    FirebaseDatabase firebaseDatabases;
    DatabaseReference databaseReferences;
    String emailid,email_password;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register);

        register=findViewById(R.id.register);
        mailid=findViewById(R.id.mail);
        username=findViewById(R.id.user);
        idnumber=findViewById(R.id.vecidnumber);
        Password=findViewById(R.id.password);
        mobilenumber=findViewById(R.id.mobilenumber);
        department=findViewById(R.id.spinner4);
        final MediaPlayer mp = MediaPlayer.create(this, R.raw.buttonsound2);

        List<String> categories=new ArrayList<>();
        //spinner items
        categories.add(0,"Department");
        categories.add("CSE");
        categories.add("AUTO");
        categories.add("MECH");
        categories.add("CIVIL");
        categories.add("EEE");
        categories.add("EIE");
        categories.add("ECE");
        categories.add("IT");
        categories.add("CHEMISTRY");
        categories.add("PHYSICS");
        categories.add("MATHEMATICS");

        ArrayAdapter<String> dataAdapter;
        dataAdapter=new ArrayAdapter(this,android.R.layout.simple_spinner_item,categories);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        department.setAdapter(dataAdapter);
        department.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                if(parent.getItemAtPosition(position).equals("Department")){
                    //do nothing
                    dept=null;
                }
                else{
                    //on selecting sppiner item
                    String item=parent.getItemAtPosition(position).toString();
                    //show spiner item
                    Toast.makeText(parent.getContext(),"selected:"+item, Toast.LENGTH_SHORT).show();
                    //anything u want do here
                    dept=department.getSelectedItem().toString();
                }
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                //TODO AUTOGENERATED METHOD DO HERE

            }
        });

        fAuth=FirebaseAuth.getInstance();
        databaseReferences=FirebaseDatabase.getInstance().getReference("signup");
        register.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mp.start();
                final String Username = username.getText().toString();
                final String IDNo = idnumber.getText().toString();
                final String Emailid = mailid.getText().toString();
                final String mobno = mobilenumber.getText().toString();
                emailid = mailid.getText().toString();
                email_password = Password.getText().toString();
                if (username.length() == 0) {
                    username.setError("Enter Username!");
                } else if (idnumber.length() == 0 ) {
                    idnumber.setError("Enter ID-no!");
                }
               else if(IDNo.contains("vec")) {
                    idnumber.setError("Please follow proper format (VEC-). VEC should be in caps!");
                }
                else if(!IDNo.contains("VEC")){
                    idnumber.setError("Please Provide your VEC Id. for betterment kindly check it out with your college id!");
                }
                else if(!IDNo.contains("-")) {
                    idnumber.setError("- symbol missing after VEC. please follow proper format (VEC-)");
                }
               else if (mailid.length() == 0) {
                    mailid.setError("Enter Mail-id!");
                } else if (Password.length() == 0) {
                    Password.setError("Enter Password!");
                } else if (mobilenumber.length() == 0 ||mobilenumber.length() != 10) {
                    mobilenumber.setError("Enter Mobile-No!");
                } else if(dept==null){
                    Toast.makeText(register.this, " select department",
                            Toast.LENGTH_LONG).show();
                }
                else{
                    fAuth.createUserWithEmailAndPassword(emailid, email_password)
                            .addOnCompleteListener(register.this, new OnCompleteListener<AuthResult>() {
                                @Override
                                public void onComplete(@NonNull Task<AuthResult> task) {

                                    if (task.isSuccessful()) {
                                        //updating values to the child class
                                        final signup info = new signup(
                                                Username,
                                                IDNo,
                                                Emailid,
                                                mobno,
                                                dept
                                        );
                                        FirebaseDatabase.getInstance().getReference("signup")
                                                .child(FirebaseAuth.getInstance().getCurrentUser().getUid())
                                                .setValue(info).addOnCompleteListener(new OnCompleteListener<Void>() {
                                            @Override
                                            public void onComplete(@NonNull Task<Void> task) {
                                                Toast.makeText(register.this, "Registration success!",
                                                        Toast.LENGTH_LONG).show();
                                                Intent intent = new Intent(register.this,Profile_page.class);
                                                startActivity(intent);
                                                finish();
                                            }
                                        });
                                    } else {
                                        Toast.makeText(register.this, " Please provide valid MailId and Password!.",
                                                Toast.LENGTH_LONG).show();
                                    }
                                }
                            });
                }
            }
        });
    }

    @Override
    public void onBackPressed(){
        super.onBackPressed();
        Intent intent=new Intent(register.this,MainActivity.class);
        startActivity(intent);
    }
}
